modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/whirlfrenzy/item-despawn-timer/issues"
license = "MIT"

[[mods]]
modId = "item_despawn_timer"
version = "${version}"
displayName = "Item Despawn Timer"
authors = "whirlfrenzy"
description = '''
Informs you about the remainder of an item's lifespan
'''
#logoFile = ""
displayTest="NONE"

[[dependencies.item_despawn_timer]]
modId = "forge"
type = "required"
versionRange = "[47.3.0,)"
ordering = "NONE"
side = "CLIENT"
mandatory = true

[[dependencies.item_despawn_timer]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,1.20.1]"
ordering = "NONE"
side = "BOTH"
mandatory = true

[[mixins]]
config = "item-despawn-timer.mixins.json"

[[mixins]]
config = "item-despawn-timer.forge.mixins.json"