name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [
          17,
        ]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts (common)
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts (Common)
          path: common/build/libs/
      - name: capture build artifacts (fabric)
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts (Fabric)
          path: fabric/build/libs/
      - name: capture build artifacts (neoforge)
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts (NeoForge)
          path: neoforge/build/libs/